[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = ["generated.nix"]

[formatter.python3]
command = "black"
includes = ["*.py"]
options = ["--line-length", "100"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

# [formatter.sh]
# command = "shfmt"
# includes = ["*.sh"]
