[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.python3]
command = "black"
includes = ["*.py"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.sh]
command = "shfmt"
includes = ["*.sh"]
