name: "setup"
description: "Common steps for workflows"
runs:
  using: "composite"
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        install_url: https://releases.nixos.org/nix/nix-2.8.0/install
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes
          extra-substituters = https://viperml.cachix.org
          extra-trusted-public-keys = viperml.cachix.org-1:qZhKBMTfmcLL+OG6fj/hzsMEedgKvZVFRRAhq7j8Vh8=
          extra-substituters = https://nix-community.cachix.org
          extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
    - name: Set up cachix
      uses: cachix/cachix-action@master
      with:
        name: viperml
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pathsToPush: result
