# ~/.config/starship.toml

# Use custom format
format = """
$custom\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$python\
$terraform\
$package\
$jobs\
$directory\
$shlvl\
$cmd_duration
[λ](bold) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
style = "bold blue"
read_only = " "
truncate_to_repo = false
truncation_length = 0
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "==>  [$symbol$branch]($style) "
symbol = ""

[git_status]
format = '([\[$conflicted$stashed$deleted$renamed$modified$staged$untracked$ahead_behind \]]($style) )'
conflicted = "="
ahead =" ⇡$count"
behind = " ⇣$count"
diverged = " ⇕$count"
up_to_date = ""
untracked = " ?$count"
stashed = " $$count"
modified = " !$count"
staged = " +$count"
renamed = " »$count"
deleted = " ✘$count"
style = "bold cyan"

[git_metrics]
disabled = false
# format = """\[( [+$added]($added_style))( [-$deleted]($deleted_style)) \]
format = """
([+$added]($added_style) )([-$deleted]($deleted_style))
"""

[jobs]
disabled = false
format = """==>  bg jobs: [$symbol$number]($style)
"""
number_threshold = 1
symbol = ""


[python]
format = """==> [${symbol}${pyenv_prefix}(${version} )(($virtualenv) )]($style)
"""
symbol = " "

[package]
format = """==> [$symbol$version]($style)
"""
symbol = " "

[cmd_duration]
min_time = 60_000

[shlvl]
disabled = false
format = '\[ $shlvl \]'


[terraform]
format = """==> [$symbol$workspace]($style)
"""
symbol = "練 "
