theme = "ayu_evolve"

[editor]
line-number = "relative"
cursorline = true
true-color = true

[editor.lsp]
display-messages = true

[keys.normal]
"C" = "select_textobject_inner"
Z = { Z = ":wq", Q = ":q!" }
