[sharedtags]
src.git = "https://github.com/Drauthius/awesome-sharedtags"
fetch.github = "Drauthius/awesome-sharedtags"
[awesome-wm-widgets]
src.git = "https://github.com/streetturtle/awesome-wm-widgets"
fetch.github = "streetturtle/awesome-wm-widgets"
[freedesktop]
src.git = "https://github.com/lcpz/awesome-freedesktop"
fetch.github = "lcpz/awesome-freedesktop"
[revelation]
src.git = "https://github.com/guotsuan/awesome-revelation"
fetch.github = "guotsuan/awesome-revelation"
[lain]
src.git = "https://github.com/lcpz/lain"
fetch.github = "lcpz/lain"
[bling]
src.git = "https://github.com/BlingCorp/bling"
fetch.github = "BlingCorp/bling"
