[zsh-completions]
src.github = "zsh-users/zsh-completions"
fetch.github = "zsh-users/zsh-completions"

[zsh-syntax-highlighting]
src.git = "https://github.com/zsh-users/zsh-syntax-highlighting"
fetch.github = "zsh-users/zsh-syntax-highlighting"

[zsh-autosuggestions]
src.git = "https://github.com/zsh-users/zsh-autosuggestions"
fetch.github = "zsh-users/zsh-autosuggestions"

[zsh-abbr]
src.github = "olets/zsh-abbr"
fetch.github = "olets/zsh-abbr"
