[zsh-completions]
src.github = "zsh-users/zsh-completions"
fetch.github = "zsh-users/zsh-completions"

[zsh-syntax-highlighting]
src.git = "https://github.com/zsh-users/zsh-syntax-highlighting"
fetch.github = "zsh-users/zsh-syntax-highlighting"

[zsh-autosuggestions]
src.git = "https://github.com/zsh-users/zsh-autosuggestions"
fetch.github = "zsh-users/zsh-autosuggestions"

[zsh-edit]
src.git = "https://github.com/marlonrichert/zsh-edit"
fetch.github = "marlonrichert/zsh-edit"
