[buildPlans.iosevka-quasi]
family = "iosevka-quasi"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-quasi.variants]
  inherits = "ss14"

  [buildPlans.iosevka-quasi.ligations]
  inherits = "dlig"

  [buildPlans.iosevka-quasi.variants.design]
    zero = "slashed"

[buildPlans.iosevka-quasi.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-quasi.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-quasi.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-quasi.weights.bold]
shape = 700
menu = 700
css = 700
