name: Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 */15 * *"

jobs:
  branches:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.9
        with:
          repo_token: ${{ github.token }}
          date: '1 months ago'
          dry_run: false
          delete_tags: false
          exclude_open_pr_branches: true

  code:
    name: Run cleanup script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix

    - name: Run cleanup script
      run: nix run .#cleanup

    - name: Run formatting script
      run: nix run .#format

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: '[automatic] flake cleanup'
        commit-message: |
          - Flake cleanup

          Auto-generated in GH actions

          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        body: |
          Automatic flake cleanup
        author: GitHub <noreply@github.com>
        branch: cleanup-flake
        branch-suffix: timestamp
        delete-branch: true
