name: "Flake cache"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Flake Check"]
    types:
      - completed

jobs:
  main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Main job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v16
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.6.0pre20220122_c9a4ddb/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v10
      with:
        name: viperml
        extraPullNames: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: ./bin/build-flake.sh
