name: "Flake Check"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  builds:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v16
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.6.0pre20211228_ed3bc63/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix flake check
