name: pr-check

on:
  pull_request:
  workflow_dispatch:

jobs:
  check_flake:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - name: Flake check
      run: nix flake check
