name: Update all

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *"
    - cron: "0 4 15 * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nix
      uses: ./.github/actions/install-nix

    - name: Pre-build update script
      run: nix build .#dotfiles-update

    - name: Run update script
      run: ./result/bin/dotfiles-update $PWD

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: '${{ secrets.PAT }}'
        title: '[automatic] flake update'
        commit-message: |
          Update all


          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        author: GitHub <noreply@github.com>
        branch: update
        branch-suffix: timestamp
        delete-branch: true
