name: update

on:
  workflow_dispatch:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      scripts: ${{ steps.find_scripts.outputs.scripts }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - id: find_scripts
      name: Find updater scripts
      run: nix run .#python3 -- ./bin/update_generate_matrix.py

  update:
    runs-on: ubuntu-latest
    needs: [generate_matrix]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        script: ${{fromJson(needs.generate_matrix.outputs.scripts)}}
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Install nix
      uses: ./.github/actions/install-nix
    - name: Run update script
      run: |
        nix profile install \
          .#update-nix-fetchgit \
          .#nix-update \
          .#git-extras
        cd $(dirname ${{ matrix.script }})
        sh -c "./$(basename ${{ matrix.script }})"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PAT }}
        title: '[Auto-update] ${{ matrix.script }}'
        commit-message: |
          Automatic update for ${{ matrix.script }}
        body: |
          I ran the update script sucessfully
        delete-branch: true
