[[apps]]
ref = "com.google.Chrome/x86_64/beta"
origin = "flathub-beta"

[[apps]]
ref = "org.mozilla.firefox/x86_64/stable"
origin = "flathub-beta"

[[apps]]
ref = "com.getmailspring.Mailspring/x86_64/stable"
origin = "flathub"

[[apps]]
ref = "com.github.tchx84.Flatseal/x86_64/stable"
origin = "flathub"

[[remotes]]
name = "flathub"
url = "https://dl.flathub.org/repo"

[[remotes]]
name = "flathub-beta"
url = "https://dl.flathub.org/beta-repo"
