overrides = [
  "--filesystem=/nix/store:ro",
]

### REMOTES

[[remotes]]
name = "flathub"
url = "https://dl.flathub.org/repo"

[[remotes]]
name = "flathub-beta"
url = "https://dl.flathub.org/beta-repo"

### APPS

[[apps]]
origin = "flathub"
ref = "com.github.tchx84.Flatseal/x86_64/stable"

[[apps]]
origin = "flathub"
ref = "com.valvesoftware.Steam/x86_64/stable"

# [[apps]]
# origin = "flathub"
# ref = "org.fedoraproject.MediaWriter/x86_64/stable"

[[apps]]
origin = "flathub"
ref = "com.usebottles.bottles/x86_64/stable"

# [[apps]]
# origin = "flathub"
# ref = "com.getpostman.Postman/x86_64/stable"
